Feat/auth
Yoha485/Budgets pull request #2
Opened 2022-04-05 11:59 UTC by Yoha485

JWT auth

2022-04-05 12:28 UTC, ignavan39 requested changes

2022-04-05 12:28 UTC, ignavan39 commented on backend/dist/common/abstract-entity.d.ts
> +export declare abstract class AbstractEntity extends BaseEntity {
Я бы сразу с реализацией функционала ормки делал
Типо добавь декораторы
```typescript
@UpdatedDateTime 
```
Или как то так ну и по аналогии primary key

2022-04-05 12:28 UTC, ignavan39 commented on backend/src/app.module.ts
> +import { ConfigModule } from '@nestjs/config';
Удали если не используется

2022-04-05 12:28 UTC, ignavan39 commented on backend/src/auth/auth/auth.controller.ts
> +	@HttpCode(200)
Зачем этот?

2022-04-05 12:28 UTC, ignavan39 commented on backend/src/auth/auth/auth.module.ts
> +				expiresIn: 36000,
В конфиги

2022-04-05 12:28 UTC, ignavan39 commented on backend/src/auth/auth/auth.module.ts
> +      secret: String(process.env.SECRET_KEY),
А если не найдётся что произойдет?

2022-04-05 12:28 UTC, ignavan39 commented on backend/src/auth/auth/auth.service.ts
> +      console.log(err)
Удали или добавь нормальный логгер

2022-04-05 12:28 UTC, ignavan39 commented on backend/src/auth/auth/auth.service.ts
> +			if (err.code === '23505') {
Ох уж эти магические числа, занеси в enum что-ли

2022-04-05 12:28 UTC, ignavan39 commented on backend/src/auth/auth/auth.service.ts
> +    } catch (err) {
Зачем нужен toJson, он же и так норм Json соберёт

2022-04-05 12:28 UTC, ignavan39 commented on backend/src/main.ts
> +import { INestApplication, ValidationPipe } from '@nestjs/common';
Удали ValidationPipe если не используется

2022-04-05 12:28 UTC, ignavan39 commented on backend/src/main.ts
> +		origin: '*',
В конфиги

2022-04-05 12:28 UTC, ignavan39 commented on backend/src/user/user.dto.ts
> +
Пробел тут нужен?

2022-04-05 12:28 UTC, ignavan39 commented on backend/src/user/user.entity.ts
> +  toJson(): Record<string, any>{
Зачем это?

2022-04-05 12:28 UTC, ignavan39 commented on backend/src/user/user.entity.ts
> +  @Column({ unique: true })
Вынеси 
```typescript
@Unique()
```
На уровне класса чтобы можно было ему нормальное имя задать и не пологаться на нейминг орм

2022-04-05 12:28 UTC, ignavan39 commented on backend/src/user/user.entity.ts
> +  username: string;
Аналогично

2022-04-05 12:34 UTC, Yoha485 commented on backend/dist/common/abstract-entity.d.ts
> +export declare abstract class AbstractEntity extends BaseEntity {
Не понял..

2022-04-05 21:43 UTC, ignavan39 requested changes

2022-04-05 21:43 UTC, ignavan39 commented on backend/src/auth/auth/auth.controller.ts
> +import { Body, Controller, HttpCode, Post } from '@nestjs/common';
HttpCode не используется

2022-04-05 21:43 UTC, ignavan39 commented on backend/src/auth/auth/jwt.strategy.ts
> +      secretOrKey: process.env.SECRET_KEY,
Что будет если не найдётся ?

2022-04-05 21:43 UTC, ignavan39 commented on backend/src/database-connection.service.ts
> +			host: process.env.DATABASE_HOST,
Вынеси сразу в нормальный config service

2022-04-05 21:43 UTC, ignavan39 commented on backend/src/main.ts
> +		origin: process.env.CORS_ORIGIN || '*',
Тоже

2022-04-07 19:25 UTC, ignavan39 approved these changes

2022-04-07 19:27 UTC, ignavan39 commented on backend/package.json
> +    "mysql2": "^2.3.3",
А это используется?

2022-04-10 13:05 UTC, merged